// <auto-generated />
namespace Democracy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _20190208 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20190208));
        
        string IMigrationMetadata.Id
        {
            get { return "201902081150503_20190208"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
